server:
  port: 8081

spring:
  application:
    name: lightbatis-samples
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java, src/main/resources
      exclude: WEB-INF/**
  datasource:
#    url: jdbc:mysql://118.31.33.203:13306/crmszt?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&nullCatalogMeansCurrent=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 6BqFNjYhiQkg
    url: jdbc:mysql://localhost:3306/lightbatisdb?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    #type: com.alibaba.druid.pool.DruidDataSource
#    username: postgres
#    password: 123456
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/demo
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/vrcodedb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    #方言
    #dialect: postgresql
    hikari: 
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
    


springfox:
  documentation:
    swagger:
      v2:
        path: /apidoc
#mybatis: 
#   configuration: org.apache.ibatis.session.Configuration

#lightbatis:
#  mappers: titan.common.dal.mapper.QueryMapper

#logging:
#  config: classpath:log4j2-spring.xml 
  #config: classpath:logback-spring.xml 

logging:
  config: classpath:logback-spring.xml 
  level: 
    org.springframework: INFO
    titan.lightbatis.mybatis.provider.impl: INFO
snowflake:
  workerId: 1
  datacenterId: 1
mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      
#dal:
#  base-package: com.aeotrade.provider
   