server:
  port: 8082

spring:
  application:
    name: titan-mybatis-web
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java, src/main/resources
      exclude: WEB-INF/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://39.104.25.76:13306/qutmtrade?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&zeroDateTimeBehavior=convertToNull
#    username: bitrade
#    password: bitrade093867koio
    url: jdbc:mysql://127.0.0.1:3306/lightbatisdb?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      validation-query: SELECT 1
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000


springfox:
  documentation:
    swagger:
      v2:
        path: /apidoc

#logging:
#  config: classpath:logback-spring.xml

mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

snowflake:
  workerId: 1
  datacenterId: 1