server:
  port: 8082

spring:
  application:
    name: titan-mybatis-web
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java, src/main/resources
      exclude: WEB-INF/**
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/demo
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atnong_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useInformationSchema=true
    #方言
    #dialect: postgresql
    hikari: 
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
    


springfox:
  documentation:
    swagger:
      v2:
        path: /apidoc

#logging:
#  config: classpath:logback-spring.xml

mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

snowflake:
  workerId: 1
  datacenterId: 1